# Generated by Django 3.1.1 on 2020-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
