# Generated by Django 3.1.1 on 2020-10-21 09:12

from django.db import migrations, models
import marketingemails.customModelFields


class Migration(migrations.Migration):

    dependencies = [
        ('marketingemails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='location_of_interest',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_link',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='participated_campaigns',
            field=marketingemails.customModelFields.CommaSepField(default='NULL'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
