# Generated by Django 3.1.1 on 2020-10-22 09:34

from django.db import migrations
import marketingemails.customModelFields


class Migration(migrations.Migration):

    dependencies = [
        ('marketingemails', '0003_campaigns_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='email_opens',
            field=marketingemails.customModelFields.HashmapField(blank=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='link_opens',
            field=marketingemails.customModelFields.HashmapField(blank=True),
        ),
    ]
