# Generated by Django 3.1.1 on 2020-10-22 09:36

from django.db import migrations
import marketingemails.customModelFields


class Migration(migrations.Migration):

    dependencies = [
        ('marketingemails', '0004_auto_20201022_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='audience',
            field=marketingemails.customModelFields.CommaSepField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='parent_campaigns',
            field=marketingemails.customModelFields.CommaSepField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='participated_campaigns',
            field=marketingemails.customModelFields.CommaSepField(blank=True),
        ),
    ]
