# Generated by Django 3.1.1 on 2020-11-09 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketingemails', '0005_auto_20201022_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCampaign',
            fields=[
                ('scheduled_timestamp', models.DateTimeField(db_index=True)),
                ('data', models.TextField()),
                ('type', models.PositiveSmallIntegerField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='campaign_to_schedule_queue', serialize=False, to='marketingemails.campaigns')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaigns',
            name='launch_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
