# Generated by Django 3.1.1 on 2020-11-10 07:56

from django.db import migrations, models
import marketingemails.customModelFields


class Migration(migrations.Migration):

    dependencies = [
        ('marketingemails', '0006_auto_20201109_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcampaign',
            name='type',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='future_campaigns',
            field=marketingemails.customModelFields.CommaSepField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='launch_datetime',
            field=models.DateTimeField(blank=True, verbose_name='date launched'),
        ),
    ]
